// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block.proto

/*
Package corepb is a generated protocol buffer package.

It is generated from these files:
	block.proto

It has these top-level messages:
	Account
	Data
	Transaction
	BlockHeader
	Block
	NetBlocks
	NetBlock
*/
package corepb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Balance    []byte `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce      uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	VarsHash   []byte `protobuf:"bytes,3,opt,name=vars_hash,json=varsHash,proto3" json:"vars_hash,omitempty"`
	BirthPlace []byte `protobuf:"bytes,4,opt,name=birth_place,json=birthPlace,proto3" json:"birth_place,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{0} }

func (m *Account) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetVarsHash() []byte {
	if m != nil {
		return m.VarsHash
	}
	return nil
}

func (m *Account) GetBirthPlace() []byte {
	if m != nil {
		return m.BirthPlace
	}
	return nil
}

type Data struct {
	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{1} }

func (m *Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Data) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Transaction struct {
	Hash      []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From      []byte `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        []byte `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value     []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Nonce     uint64 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp int64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data      *Data  `protobuf:"bytes,7,opt,name=data" json:"data,omitempty"`
	ChainId   uint32 `protobuf:"varint,8,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Alg       uint32 `protobuf:"varint,9,opt,name=alg,proto3" json:"alg,omitempty"`
	Sign      []byte `protobuf:"bytes,10,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{2} }

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetAlg() uint32 {
	if m != nil {
		return m.Alg
	}
	return 0
}

func (m *Transaction) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type BlockHeader struct {
	Hash                  []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash            []byte `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Nonce                 uint64 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Coinbase              []byte `protobuf:"bytes,4,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	Timestamp             int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId               uint32 `protobuf:"varint,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	StateRoot             []byte `protobuf:"bytes,7,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	TxsRoot               []byte `protobuf:"bytes,8,opt,name=txs_root,json=txsRoot,proto3" json:"txs_root,omitempty"`
	DynastyParentHash     []byte `protobuf:"bytes,9,opt,name=dynasty_parent_hash,json=dynastyParentHash,proto3" json:"dynasty_parent_hash,omitempty"`
	DynastyRoot           []byte `protobuf:"bytes,10,opt,name=dynasty_root,json=dynastyRoot,proto3" json:"dynasty_root,omitempty"`
	NextDynastyRoot       []byte `protobuf:"bytes,11,opt,name=next_dynasty_root,json=nextDynastyRoot,proto3" json:"next_dynasty_root,omitempty"`
	DynastyCandidatesRoot []byte `protobuf:"bytes,12,opt,name=dynasty_candidates_root,json=dynastyCandidatesRoot,proto3" json:"dynasty_candidates_root,omitempty"`
	DepositRoot           []byte `protobuf:"bytes,13,opt,name=deposit_root,json=depositRoot,proto3" json:"deposit_root,omitempty"`
	PrepareVotesRoot      []byte `protobuf:"bytes,14,opt,name=prepare_votes_root,json=prepareVotesRoot,proto3" json:"prepare_votes_root,omitempty"`
	CommitVotesRoot       []byte `protobuf:"bytes,15,opt,name=commit_votes_root,json=commitVotesRoot,proto3" json:"commit_votes_root,omitempty"`
	ChangeVotesRoot       []byte `protobuf:"bytes,16,opt,name=change_votes_root,json=changeVotesRoot,proto3" json:"change_votes_root,omitempty"`
	AbdicateVotesRoot     []byte `protobuf:"bytes,17,opt,name=abdicate_votes_root,json=abdicateVotesRoot,proto3" json:"abdicate_votes_root,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{3} }

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetCoinbase() []byte {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *BlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeader) GetTxsRoot() []byte {
	if m != nil {
		return m.TxsRoot
	}
	return nil
}

func (m *BlockHeader) GetDynastyParentHash() []byte {
	if m != nil {
		return m.DynastyParentHash
	}
	return nil
}

func (m *BlockHeader) GetDynastyRoot() []byte {
	if m != nil {
		return m.DynastyRoot
	}
	return nil
}

func (m *BlockHeader) GetNextDynastyRoot() []byte {
	if m != nil {
		return m.NextDynastyRoot
	}
	return nil
}

func (m *BlockHeader) GetDynastyCandidatesRoot() []byte {
	if m != nil {
		return m.DynastyCandidatesRoot
	}
	return nil
}

func (m *BlockHeader) GetDepositRoot() []byte {
	if m != nil {
		return m.DepositRoot
	}
	return nil
}

func (m *BlockHeader) GetPrepareVotesRoot() []byte {
	if m != nil {
		return m.PrepareVotesRoot
	}
	return nil
}

func (m *BlockHeader) GetCommitVotesRoot() []byte {
	if m != nil {
		return m.CommitVotesRoot
	}
	return nil
}

func (m *BlockHeader) GetChangeVotesRoot() []byte {
	if m != nil {
		return m.ChangeVotesRoot
	}
	return nil
}

func (m *BlockHeader) GetAbdicateVotesRoot() []byte {
	if m != nil {
		return m.AbdicateVotesRoot
	}
	return nil
}

type Block struct {
	Header       *BlockHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	Height       uint64         `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{4} }

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type NetBlocks struct {
	From   string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Nonce  uint64   `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Blocks []*Block `protobuf:"bytes,3,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *NetBlocks) Reset()                    { *m = NetBlocks{} }
func (m *NetBlocks) String() string            { return proto.CompactTextString(m) }
func (*NetBlocks) ProtoMessage()               {}
func (*NetBlocks) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{5} }

func (m *NetBlocks) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *NetBlocks) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *NetBlocks) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type NetBlock struct {
	From  string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Block *Block `protobuf:"bytes,3,opt,name=block" json:"block,omitempty"`
}

func (m *NetBlock) Reset()                    { *m = NetBlock{} }
func (m *NetBlock) String() string            { return proto.CompactTextString(m) }
func (*NetBlock) ProtoMessage()               {}
func (*NetBlock) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{6} }

func (m *NetBlock) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *NetBlock) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *NetBlock) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "corepb.Account")
	proto.RegisterType((*Data)(nil), "corepb.Data")
	proto.RegisterType((*Transaction)(nil), "corepb.Transaction")
	proto.RegisterType((*BlockHeader)(nil), "corepb.BlockHeader")
	proto.RegisterType((*Block)(nil), "corepb.Block")
	proto.RegisterType((*NetBlocks)(nil), "corepb.NetBlocks")
	proto.RegisterType((*NetBlock)(nil), "corepb.NetBlock")
}

func init() { proto.RegisterFile("block.proto", fileDescriptorBlock) }

var fileDescriptorBlock = []byte{
	// 651 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcb, 0x8e, 0xd4, 0x3a,
	0x10, 0x55, 0xfa, 0x9d, 0x4a, 0xe6, 0xd1, 0x9e, 0xfb, 0xc8, 0xbd, 0x80, 0x26, 0x04, 0x21, 0xb5,
	0x06, 0xd4, 0x8b, 0x01, 0xc1, 0x1a, 0x98, 0xc5, 0xb0, 0x41, 0xa3, 0x08, 0x21, 0x21, 0x21, 0x45,
	0x95, 0x07, 0x9d, 0x88, 0x6e, 0x3b, 0x8a, 0x3d, 0xc3, 0xf4, 0x07, 0xf0, 0xc3, 0x6c, 0xd8, 0x22,
	0x97, 0x9d, 0xee, 0x04, 0x66, 0xc3, 0xce, 0x55, 0xe7, 0x54, 0xf9, 0x1c, 0xbb, 0x6c, 0xf0, 0xd2,
	0xb5, 0xc8, 0xbe, 0x2c, 0xeb, 0x46, 0x28, 0xc1, 0x26, 0x99, 0x68, 0x8a, 0x3a, 0x8d, 0xbe, 0xc2,
	0xf4, 0x55, 0x96, 0x89, 0x6b, 0xae, 0x58, 0x00, 0xd3, 0x14, 0xd7, 0xc8, 0xb3, 0x22, 0x70, 0x42,
	0x67, 0xe1, 0xc7, 0x6d, 0xc8, 0xfe, 0x82, 0x31, 0x17, 0x3a, 0x3f, 0x08, 0x9d, 0xc5, 0x28, 0x36,
	0x01, 0xbb, 0x07, 0xee, 0x0d, 0x36, 0x32, 0x29, 0x51, 0x96, 0xc1, 0x90, 0x2a, 0x66, 0x3a, 0x71,
	0x89, 0xb2, 0x64, 0xa7, 0xe0, 0xa5, 0x55, 0xa3, 0xca, 0xa4, 0x5e, 0x63, 0x56, 0x04, 0x23, 0x82,
	0x81, 0x52, 0x57, 0x3a, 0x13, 0x3d, 0x87, 0xd1, 0x05, 0x2a, 0x64, 0x0c, 0x46, 0x6a, 0x5b, 0x9b,
	0x2d, 0xdd, 0x98, 0xd6, 0x5a, 0x49, 0x8d, 0xdb, 0xb5, 0xc0, 0x9c, 0x76, 0xf4, 0xe3, 0x36, 0x8c,
	0xbe, 0x3b, 0xe0, 0xbd, 0x6f, 0x90, 0x4b, 0xcc, 0x54, 0x25, 0xb8, 0xae, 0xa6, 0xed, 0x8d, 0x60,
	0x5a, 0xeb, 0xdc, 0xe7, 0x46, 0x6c, 0x6c, 0x29, 0xad, 0xd9, 0x21, 0x0c, 0x94, 0xb0, 0x22, 0x07,
	0x4a, 0x68, 0x47, 0x37, 0xb8, 0xbe, 0x6e, 0x85, 0x99, 0x60, 0xef, 0x73, 0xdc, 0xf5, 0x79, 0x1f,
	0x5c, 0x55, 0x6d, 0x0a, 0xa9, 0x70, 0x53, 0x07, 0x93, 0xd0, 0x59, 0x0c, 0xe3, 0x7d, 0x82, 0x85,
	0x30, 0xca, 0x51, 0x61, 0x30, 0x0d, 0x9d, 0x85, 0x77, 0xee, 0x2f, 0xcd, 0xb9, 0x2e, 0xb5, 0xb7,
	0x98, 0x10, 0xf6, 0x1f, 0xcc, 0xb2, 0x12, 0x2b, 0x9e, 0x54, 0x79, 0x30, 0x0b, 0x9d, 0xc5, 0x41,
	0x3c, 0xa5, 0xf8, 0x6d, 0xce, 0x8e, 0x61, 0x88, 0xeb, 0x55, 0xe0, 0x52, 0x56, 0x2f, 0xb5, 0x78,
	0x59, 0xad, 0x78, 0x00, 0x46, 0xbc, 0x5e, 0x47, 0x3f, 0x46, 0xe0, 0xbd, 0xd6, 0x77, 0x77, 0x59,
	0x60, 0x5e, 0x34, 0x77, 0x9a, 0x3e, 0x05, 0xaf, 0xc6, 0xa6, 0xe0, 0xca, 0x5c, 0x87, 0xf1, 0x0e,
	0x26, 0x45, 0x17, 0xb2, 0xf3, 0x36, 0xec, 0x7a, 0xfb, 0x1f, 0x66, 0x99, 0xa8, 0x78, 0x8a, 0xb2,
	0x3d, 0x8a, 0x5d, 0xdc, 0xf7, 0x3d, 0xfe, 0xd5, 0x77, 0xd7, 0xd5, 0xa4, 0xef, 0xea, 0x01, 0x80,
	0x54, 0xa8, 0x8a, 0xa4, 0x11, 0x42, 0xd1, 0xc1, 0xf8, 0xb1, 0x4b, 0x99, 0x58, 0x08, 0xa5, 0x2b,
	0xd5, 0xad, 0x34, 0xe0, 0xcc, 0x5c, 0xaf, 0xba, 0x95, 0x04, 0x2d, 0xe1, 0x24, 0xdf, 0x72, 0x94,
	0x6a, 0x9b, 0x74, 0xdd, 0xb8, 0xc4, 0x9a, 0x5b, 0xe8, 0x6a, 0x6f, 0xea, 0x21, 0xf8, 0x2d, 0x9f,
	0xda, 0x99, 0x53, 0xf3, 0x6c, 0x8e, 0x5a, 0x9e, 0xc1, 0x9c, 0x17, 0xb7, 0x2a, 0xe9, 0xf1, 0x3c,
	0xe2, 0x1d, 0x69, 0xe0, 0xa2, 0xc3, 0x7d, 0x01, 0xff, 0xb6, 0xb4, 0x0c, 0x79, 0x5e, 0xe5, 0xa8,
	0x0a, 0x2b, 0xd4, 0xa7, 0x8a, 0xbf, 0x2d, 0xfc, 0x66, 0x87, 0x52, 0x9d, 0x96, 0x51, 0xd4, 0x42,
	0x56, 0xca, 0x90, 0x0f, 0xac, 0x0c, 0x93, 0x23, 0xca, 0x53, 0x60, 0x75, 0x53, 0x68, 0x53, 0xc9,
	0x8d, 0xd8, 0x75, 0x3d, 0x24, 0xe2, 0xb1, 0x45, 0x3e, 0x88, 0xb6, 0xe1, 0x19, 0xcc, 0x33, 0xb1,
	0xd9, 0x54, 0xaa, 0x4b, 0x3e, 0x32, 0xa2, 0x0d, 0xd0, 0xe7, 0x96, 0xc8, 0x57, 0xbd, 0xc6, 0xc7,
	0x96, 0x4b, 0xc0, 0x9e, 0xbb, 0x84, 0x13, 0x4c, 0xf3, 0x2a, 0xd3, 0x97, 0xd3, 0x61, 0xcf, 0xcd,
	0xf9, 0xb6, 0xd0, 0x8e, 0x1f, 0x7d, 0x73, 0x60, 0x4c, 0x93, 0xc7, 0x9e, 0xc0, 0xa4, 0xa4, 0xe9,
	0xa3, 0xa9, 0xf3, 0xce, 0x4f, 0xda, 0x41, 0xef, 0x0c, 0x66, 0x6c, 0x29, 0xec, 0x25, 0xf8, 0x6a,
	0xff, 0x48, 0x65, 0x30, 0x08, 0x87, 0xdd, 0x92, 0xce, 0x03, 0x8e, 0x7b, 0x44, 0xf6, 0x8f, 0xde,
	0xa5, 0x5a, 0x95, 0xca, 0x4e, 0xa9, 0x8d, 0xa2, 0x4f, 0xe0, 0xbe, 0x2b, 0x14, 0x6d, 0x25, 0x77,
	0xef, 0xdb, 0xfe, 0x18, 0xf4, 0xbe, 0xef, 0xfe, 0xa1, 0x1e, 0xc3, 0x84, 0xfe, 0x3c, 0x19, 0x0c,
	0x49, 0xc1, 0x41, 0x4f, 0x74, 0x6c, 0xc1, 0xe8, 0x23, 0xcc, 0xda, 0xee, 0x7f, 0xd0, 0xfc, 0x11,
	0x8c, 0xa9, 0x9e, 0xa4, 0xfe, 0xd6, 0xdb, 0x60, 0xe9, 0x84, 0x7e, 0xdb, 0x67, 0x3f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x96, 0x17, 0xf9, 0x0e, 0x7c, 0x05, 0x00, 0x00,
}
