// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dynasty.proto

package corepb

import (
	fmt "fmt"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type Dynasty struct {
	// dynasty meta
	Meta *DynastyMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// candidate dynasty
	Candidate []*DynastyCandidate `protobuf:"bytes,2,rep,name=candidate,proto3" json:"candidate,omitempty"`
}

func (m *Dynasty) Reset() { *m = Dynasty{} }
func (m *Dynasty) String() string {
	if b, err := m.Marshal(); err == nil {
		if b == nil {
			return string("nil")
		}
		return string(b)
	}
	return string("error")
}
func (*Dynasty) ProtoMessage() {}

func (m *Dynasty) GetMeta() *DynastyMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Dynasty) GetCandidate() []*DynastyCandidate {
	if m != nil {
		return m.Candidate
	}
	return nil
}

type DynastyMeta struct {
	// ChainID.
	ChainId uint32 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *DynastyMeta) Reset() { *m = DynastyMeta{} }
func (m *DynastyMeta) String() string {
	if b, err := m.Marshal(); err == nil {
		if b == nil {
			return string("nil")
		}
		return string(b)
	}
	return string("error")
}
func (*DynastyMeta) ProtoMessage() {}

func (m *DynastyMeta) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

type DynastyCandidate struct {
	// effective dynasty
	Serial uint64 `protobuf:"varint,1,opt,name=serial,proto3" json:"serial,omitempty"`
	// dpos dynasty address
	Dynasty []string `protobuf:"bytes,2,rep,name=dynasty,proto3" json:"dynasty,omitempty"`
}

func (m *DynastyCandidate) Reset() { *m = DynastyCandidate{} }
func (m *DynastyCandidate) String() string {
	if b, err := m.Marshal(); err == nil {
		if b == nil {
			return string("nil")
		}
		return string(b)
	}
	return string("error")
}
func (*DynastyCandidate) ProtoMessage() {}

func (m *DynastyCandidate) GetSerial() uint64 {
	if m != nil {
		return m.Serial
	}
	return 0
}

func (m *DynastyCandidate) GetDynasty() []string {
	if m != nil {
		return m.Dynasty
	}
	return nil
}

func (m *Dynasty) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, ErrNilDynasty
	}
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Dynasty) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Meta != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDynasty(dAtA, i, uint64(m.Meta.Size()))
		n1, err := m.Meta.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Candidate) > 0 {
		for _, msg := range m.Candidate {
			dAtA[i] = 0x12
			i++
			i = encodeVarintDynasty(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *DynastyMeta) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, ErrNilDynasty
	}
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DynastyMeta) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ChainId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintDynasty(dAtA, i, uint64(m.ChainId))
	}
	return i, nil
}

func (m *DynastyCandidate) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, ErrNilDynasty
	}
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DynastyCandidate) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Serial != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintDynasty(dAtA, i, uint64(m.Serial))
	}
	if len(m.Dynasty) > 0 {
		for _, s := range m.Dynasty {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func encodeVarintDynasty(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Dynasty) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Meta != nil {
		l = m.Meta.Size()
		n += 1 + l + sovDynasty(uint64(l))
	}
	if len(m.Candidate) > 0 {
		for _, e := range m.Candidate {
			l = e.Size()
			n += 1 + l + sovDynasty(uint64(l))
		}
	}
	return n
}

func (m *DynastyMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainId != 0 {
		n += 1 + sovDynasty(uint64(m.ChainId))
	}
	return n
}

func (m *DynastyCandidate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Serial != 0 {
		n += 1 + sovDynasty(uint64(m.Serial))
	}
	if len(m.Dynasty) > 0 {
		for _, s := range m.Dynasty {
			l = len(s)
			n += 1 + l + sovDynasty(uint64(l))
		}
	}
	return n
}

func sovDynasty(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozDynasty(x uint64) (n int) {
	return sovDynasty(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Dynasty) Unmarshal(dAtA []byte) error {
	l := uint32(len(dAtA))
	iNdEx := uint32(0)
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDynasty
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := uint32(wire >> 3)
		wireType := uint32(wire & 0x7)
		_ = wireType
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var msglen uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDynasty
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Meta == nil {
				m.Meta = &DynastyMeta{}
			}
			if err := m.Meta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Candidate", wireType)
			}
			var msglen uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDynasty
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Candidate = append(m.Candidate, &DynastyCandidate{})
			if err := m.Candidate[len(m.Candidate)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			return fmt.Errorf("proto: invalid data ")
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DynastyMeta) Unmarshal(dAtA []byte) error {
	l := uint32(len(dAtA))
	iNdEx := uint32(0)
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDynasty
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := uint32(wire >> 3)
		wireType := uint32(wire & 0x7)
		_ = wireType
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDynasty
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			return fmt.Errorf("proto: invalid data ")
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DynastyCandidate) Unmarshal(dAtA []byte) error {
	l := uint32(len(dAtA))
	iNdEx := uint32(0)
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDynasty
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := uint32(wire >> 3)
		wireType := uint32(wire & 0x7)
		_ = wireType
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Serial", wireType)
			}
			m.Serial = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDynasty
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Serial |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dynasty", wireType)
			}
			var stringLen uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDynasty
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			postIndex := iNdEx + stringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dynasty = append(m.Dynasty, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			return fmt.Errorf("proto: invalid data ")
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

var (
	ErrInvalidLengthDynasty = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDynasty   = fmt.Errorf("proto: integer overflow")
	ErrNilDynasty           = fmt.Errorf("proto: can not deal with nil data")
)
